"""Conformance package constants and canonical error-code strings."""

from __future__ import annotations

from pathlib import Path

from klein.common.errors import ErrorCode

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_V1_SUITE_DIR = REPO_ROOT / "tests" / "vectors" / "v1"
DEFAULT_LEGACY_SUITE_DIR = REPO_ROOT / "tests" / "vectors"

SIMULATOR_MODULE = "klein.sim.runner"

VECTOR_INDEX_INVALID = ErrorCode.VECTOR_INDEX_INVALID.value
VECTOR_METADATA_INVALID = ErrorCode.VECTOR_METADATA_INVALID.value
VECTOR_INPUT_MISSING = ErrorCode.VECTOR_INPUT_MISSING.value
VECTOR_GOLDEN_MISSING = ErrorCode.VECTOR_GOLDEN_MISSING.value
VECTOR_EVIDENCE_ASSERTION_FAILED = ErrorCode.VECTOR_EVIDENCE_ASSERTION_FAILED.value
HAIL_GOLDEN_SCHEMA_INVALID = ErrorCode.HAIL_GOLDEN_SCHEMA_INVALID.value
HAIL_CHAIN_MISSING = ErrorCode.HAIL_CHAIN_MISSING.value
HAIL_CHAIN_MISMATCH = ErrorCode.HAIL_CHAIN_MISMATCH.value
HAIL_CHAIN_INVALID = ErrorCode.HAIL_CHAIN_INVALID.value
HAIL_RUN_END_MISSING = ErrorCode.HAIL_RUN_END_MISSING.value
HAIL_LIFECYCLE_INCOMPLETE = ErrorCode.HAIL_LIFECYCLE_INCOMPLETE.value
RUN_MANIFEST_INVALID = ErrorCode.RUN_MANIFEST_INVALID.value
RUN_MANIFEST_SCHEMA_INVALID = ErrorCode.RUN_MANIFEST_SCHEMA_INVALID.value
RUN_MANIFEST_SIGNATURE_MISSING = ErrorCode.RUN_MANIFEST_SIGNATURE_MISSING.value
RUN_MANIFEST_SIGNATURE_INVALID = ErrorCode.RUN_MANIFEST_SIGNATURE_INVALID.value
RUN_MANIFEST_PAYLOAD_MISMATCH = ErrorCode.RUN_MANIFEST_PAYLOAD_MISMATCH.value
RUN_MANIFEST_LIFECYCLE_MISSING = ErrorCode.RUN_MANIFEST_LIFECYCLE_MISSING.value
RUN_MANIFEST_CHAIN_INVALID = ErrorCode.RUN_MANIFEST_CHAIN_INVALID.value
BACKEND_IDENTITY_UNTRUSTED = ErrorCode.BACKEND_IDENTITY_UNTRUSTED.value
TRUST_POLICY_INVALID = ErrorCode.TRUST_POLICY_INVALID.value
TRUST_POLICY_SCHEMA_INVALID = ErrorCode.TRUST_POLICY_SCHEMA_INVALID.value
TRUST_POLICY_KEY_NOT_FOUND = ErrorCode.TRUST_POLICY_KEY_NOT_FOUND.value
TRUST_POLICY_SCOPE_MISMATCH = ErrorCode.TRUST_POLICY_SCOPE_MISMATCH.value
TRUST_POLICY_KEY_REVOKED = ErrorCode.TRUST_POLICY_KEY_REVOKED.value
RUN_BUNDLE_INVALID = ErrorCode.RUN_BUNDLE_INVALID.value
RUN_BUNDLE_SCHEMA_INVALID = ErrorCode.RUN_BUNDLE_SCHEMA_INVALID.value
RUN_BUNDLE_MISSING_ENTRY = ErrorCode.RUN_BUNDLE_MISSING_ENTRY.value
RUN_BUNDLE_HASH_MISMATCH = ErrorCode.RUN_BUNDLE_HASH_MISMATCH.value
RUN_BUNDLE_PATH_TRAVERSAL = ErrorCode.RUN_BUNDLE_PATH_TRAVERSAL.value
RUN_BUNDLE_SIGNED_CONFORMANCE_FAILED = ErrorCode.RUN_BUNDLE_SIGNED_CONFORMANCE_FAILED.value
RUN_BUNDLE_UNSUPPORTED_FORMAT = ErrorCode.RUN_BUNDLE_UNSUPPORTED_FORMAT.value
INDEPENDENT_VERIFIER_FAILED = ErrorCode.INDEPENDENT_VERIFIER_FAILED.value
VERIFIER_BUNDLE_INVALID = ErrorCode.VERIFIER_BUNDLE_INVALID.value
VERIFIER_HAIL_INVALID = ErrorCode.VERIFIER_HAIL_INVALID.value
VERIFIER_MANIFEST_INVALID = ErrorCode.VERIFIER_MANIFEST_INVALID.value
VERIFIER_TRUST_POLICY_INVALID = ErrorCode.VERIFIER_TRUST_POLICY_INVALID.value
VERIFIER_BINDING_MISMATCH = ErrorCode.VERIFIER_BINDING_MISMATCH.value
ARTIFACT_JSON_INVALID = ErrorCode.ARTIFACT_JSON_INVALID.value
ARTIFACT_SCHEMA_INVALID = ErrorCode.ARTIFACT_SCHEMA_INVALID.value
DDI_UNSUPPORTED_PAYLOAD = ErrorCode.DDI_UNSUPPORTED_PAYLOAD.value
HAIL_SCHEMA_INVALID = ErrorCode.HAIL_SCHEMA_INVALID.value
