[package]
name = "klein-verifier-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.102"
base64 = "0.22.1"
clap = { version = "4.6.1", features = ["derive"] }
ed25519-dalek = "2.2.0"
hex = "0.4.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
sha2 = "0.11.0"
thiserror = "2.0.18"
vr-jcs = "0.4.1"
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }

[dev-dependencies]
