from enum import Enum

class ErrorCode(str, Enum):
    """
    The Source of Truth for Klein Protocol Error Codes.
    
    Categories:
    - DDI: Device Driver Interface (Hardware/Substrate)
    - PAYLOAD: artifact payload decoding and validation
    - HAIL/OBS: runtime evidence schema and logic
    - TRACE: Trace file validation
    - KCP: vector/runtime conformance
    - RUNBOOK: Orchestration errors

    Legacy aliases from the January prototype remain as explicit aliases only:
    SCI -> HAIL/KCP, DSB -> SImgB, RSB -> RImgB, LCP -> ECRP.
    """

    # --- 1. DDI: Hardware & Substrate Faults [Source: Substrate API + Vectors 018, 022, 026] ---
    # Critical hardware safety stops
    E_OVERRIDE = "E_OVERRIDE"                 # Generic driver override
    E_OVERCURRENT = "E_OVERCURRENT"           # [Source: Substrate API]
    E_UNDERVOLTAGE = "E_UNDERVOLTAGE"         # [Source: Substrate API]
    E_FRAME_TOO_FAST = "E_FRAME_TOO_FAST"     # [Source: Substrate API]
    E_CHANNEL_UNAVAILABLE = "E_CHANNEL_UNAVAILABLE" # [Source: Substrate API]
    E_CARTRIDGE_MISMATCH = "E_CARTRIDGE_MISMATCH"   # [Source: Substrate API]
    E_SENSE_UNAVAILABLE = "E_SENSE_UNAVAILABLE"     # [Source: Substrate API]
    E_EXECUTION_ABORTED = "E_EXECUTION_ABORTED"     # [Source: Substrate API] - Used for ESTOP
    
    # Capability & Binding errors
    DDI_CALIBRATION_REQUIRED = "DDI_CALIBRATION_REQUIRED" # [Vector 018]
    DDI_CALIBRATION_MISMATCH = "DDI_CALIBRATION_MISMATCH" # [Vector 026]
    DDI_SIMGB_MISMATCH = "DDI_SIMGB_MISMATCH"             # SImgB hash mismatch
    DDI_DSB_MISMATCH = "DDI_SIMGB_MISMATCH"               # Legacy alias for DDI_SIMGB_MISMATCH
    DDI_UNSUPPORTED_PAYLOAD = "DDI_UNSUPPORTED_PAYLOAD"   # [Vector 024]
    DDI_UNSUPPORTED_PROFILE = "DDI_UNSUPPORTED_PROFILE"   # [Vector 027]
    DDI_CAPABILITY_MISSING = "DDI_CAPABILITY_MISSING"     # [Vector 065] - Required for capability gating

    # --- 2. Artifact Payload Decoding & Validation [Source: Legacy Coverage Matrix] ---
    # Digest & Structure
    KAP_DIGEST_MISMATCH = "KAP_DIGEST_MISMATCH"           # [Vector 047, 048]
    KAP_MISSING_TRACE = "KAP_MISSING_TRACE"               # [Vector 029]
    
    # Payload Logic
    PAYLOAD_MALFORMED = "PAYLOAD_MALFORMED"
    PAYLOAD_INVALID_DELTA = "PAYLOAD_INVALID_DELTA"       # [Vector 010]
    PAYLOAD_OOB_PIXEL = "PAYLOAD_OOB_PIXEL"               # [Vector 011, 087]
    PAYLOAD_NONCANONICAL_ORDER = "PAYLOAD_NONCANONICAL_ORDER" # [Vector 012]
    PAYLOAD_DUPLICATE_PIXEL = "PAYLOAD_DUPLICATE_PIXEL"   # [Vector 013, 080]
    PAYLOAD_RLE_LENGTH = "PAYLOAD_RLE_LENGTH"             # [Vector 014]
    PAYLOAD_RLE_FORMAT = "PAYLOAD_RLE_FORMAT"             # [Vector 069, 071]
    PAYLOAD_RLE_INVALID_COUNT = "PAYLOAD_RLE_INVALID_COUNT" # [Vector 077]
    PAYLOAD_RLE_OVERRUN = "PAYLOAD_RLE_OVERRUN"           # [Vector 078]
    PAYLOAD_RLE_UNDERRUN = "PAYLOAD_RLE_UNDERRUN"         # [Vector 079]
    
    # Timing & Sequencing
    PAYLOAD_NONMONOTONIC_TICKS = "PAYLOAD_NONMONOTONIC_TICKS" # [Vector 015, 036]
    PAYLOAD_DUPLICATE_TICK = "PAYLOAD_DUPLICATE_TICK"         # [Vector 037]
    
    # Channel List / Muxed Specifics
    PAYLOAD_UNSUPPORTED_WAVEFORM = "PAYLOAD_UNSUPPORTED_WAVEFORM" # [Vector 016]
    PAYLOAD_CHANNEL_OOB = "PAYLOAD_CHANNEL_OOB"           # [Vector 017]
    PAYLOAD_ACTUATION_LIMIT = "PAYLOAD_ACTUATION_LIMIT"   # [Vector 025]
    PAYLOAD_CONFLICTING_STATE = "PAYLOAD_CONFLICTING_STATE" # [Vector 031]
    PAYLOAD_VOLTAGE_OOB = "PAYLOAD_VOLTAGE_OOB"           # [Vector 032]
    PAYLOAD_FREQUENCY_OOB = "PAYLOAD_FREQUENCY_OOB"       # [Vector 042]
    PAYLOAD_MISSING_COLUMN = "PAYLOAD_MISSING_COLUMN"     # [Vector 041]
    PAYLOAD_DUPLICATE_COLUMN = "PAYLOAD_DUPLICATE_COLUMN" # [Vector 060]
    PAYLOAD_INVALID_STATE = "PAYLOAD_INVALID_STATE"       # [Vector 043]
    PAYLOAD_INVALID_VALUE = "PAYLOAD_INVALID_VALUE"       # [Vector 050, 058]
    PAYLOAD_CSV_PARSE = "PAYLOAD_CSV_PARSE"               # [Vector 068]
    
    # TFT / Bitmap Specifics
    PAYLOAD_BASE64_INVALID = "PAYLOAD_BASE64_INVALID"     # [Vector 033]
    PAYLOAD_TILE_OOB = "PAYLOAD_TILE_OOB"                 # [Vector 034]
    PAYLOAD_DELTA_CONFLICT = "PAYLOAD_DELTA_CONFLICT"     # [Vector 038, 105]
    PAYLOAD_DELTA_REMOVE_MISS = "PAYLOAD_DELTA_REMOVE_MISS" # [Vector 106]
    PAYLOAD_UNSUPPORTED_FRAME_FORMAT = "PAYLOAD_UNSUPPORTED_FRAME_FORMAT"
    PAYLOAD_TILE_OVERLAP = "PAYLOAD_TILE_OVERLAP"         # [Vector 039]
    PAYLOAD_UNSUPPORTED_TILE_ENCODING = "PAYLOAD_UNSUPPORTED_TILE_ENCODING" # [Vector 040]
    PAYLOAD_UNSUPPORTED_DIMS = "PAYLOAD_UNSUPPORTED_DIMS" # [Vector 052]
    PAYLOAD_BITMAP_LENGTH = "PAYLOAD_BITMAP_LENGTH"       # [Vector 053]
    PAYLOAD_PADDING_NONZERO = "PAYLOAD_PADDING_NONZERO"   # [Vector 063]
    PAYLOAD_INVALID_OPCODE = "PAYLOAD_INVALID_OPCODE"     # [Vector 070]
    PAYLOAD_EMPTY_TILE = "PAYLOAD_EMPTY_TILE"             # [Vector 082]
    PAYLOAD_EMPTY_DELTA = "PAYLOAD_EMPTY_DELTA"           # [Vector 107]

    # --- 3. HAIL Observables & Telemetry [Source: Legacy Vectors 044-099] ---
    OBS_NONMONOTONIC_TIME = "OBS_NONMONOTONIC_TIME"       # [Vector 044]
    OBS_SCHEMA_INVALID = "OBS_SCHEMA_INVALID"             # [Vector 045, 072, 074]
    OBS_INVALID_TIMEBASE = "OBS_INVALID_TIMEBASE"         # [Vector 054]
    OBS_UNSUPPORTED_KIND = "OBS_UNSUPPORTED_KIND"         # [Vector 055]
    OBS_TYPE_MISMATCH = "OBS_TYPE_MISMATCH"               # [Vector 064, 097]
    OBS_INVALID_ENUM = "OBS_INVALID_ENUM"                 # [Vector 073]
    OBS_INVALID_VALUE = "OBS_INVALID_VALUE"               # [Vector 075, 100]

    # --- 4. TRACE: Trace File Validation [Source: Vectors 029-103] ---
    TRACE_JSON_INVALID = "TRACE_JSON_INVALID"             # [Vector 046]
    TRACE_SCHEMA_INVALID = "TRACE_SCHEMA_INVALID"         # [Vector 076]
    TRACE_INVALID_RANGE = "TRACE_INVALID_RANGE"           # [Vector 083]
    TRACE_TYPE_MISMATCH = "TRACE_TYPE_MISMATCH"           # [Vector 084, 094]
    TRACE_UNKNOWN_CHANNEL = "TRACE_UNKNOWN_CHANNEL"       # [Vector 085]
    TRACE_INVALID_ENUM = "TRACE_INVALID_ENUM"             # [Vector 091]
    TRACE_MISSING_MAPPING = "TRACE_MISSING_MAPPING"       # [Vector 092]
    TRACE_OVERLAP = "TRACE_OVERLAP"                       # [Vector 093]
    TRACE_DUPLICATE_ID = "TRACE_DUPLICATE_ID"             # [Vector 101, 102]
    TRACE_EMPTY = "TRACE_EMPTY"                           # [Vector 103]

    # --- 5. KCP Conformance, Mitigations, & Runtime [Source: Legacy Vectors 113-120] ---
    # Core Logic
    COMPARE_MISMATCH = "COMPARE_MISMATCH"                 # [Vector 120] - Output differs from expected
    CAPABILITY_MISSING = "CAPABILITY_MISSING"             # [Vector 116] - Used for SKIP status
    VECTOR_INDEX_INVALID = "VECTOR_INDEX_INVALID"
    VECTOR_METADATA_INVALID = "VECTOR_METADATA_INVALID"
    VECTOR_INPUT_MISSING = "VECTOR_INPUT_MISSING"
    VECTOR_GOLDEN_MISSING = "VECTOR_GOLDEN_MISSING"
    VECTOR_EVIDENCE_ASSERTION_FAILED = "VECTOR_EVIDENCE_ASSERTION_FAILED"
    HAIL_SCHEMA_INVALID = "HAIL_SCHEMA_INVALID"
    HAIL_JSON_INVALID = "HAIL_JSON_INVALID"
    HAIL_GOLDEN_SCHEMA_INVALID = "HAIL_GOLDEN_SCHEMA_INVALID"
    HAIL_CHAIN_MISSING = "HAIL_CHAIN_MISSING"
    HAIL_CHAIN_MISMATCH = "HAIL_CHAIN_MISMATCH"
    HAIL_CHAIN_INVALID = "HAIL_CHAIN_INVALID"
    HAIL_RUN_END_MISSING = "HAIL_RUN_END_MISSING"
    HAIL_LIFECYCLE_INCOMPLETE = "HAIL_LIFECYCLE_INCOMPLETE"
    RUN_MANIFEST_INVALID = "RUN_MANIFEST_INVALID"
    RUN_MANIFEST_SCHEMA_INVALID = "RUN_MANIFEST_SCHEMA_INVALID"
    RUN_MANIFEST_SIGNATURE_MISSING = "RUN_MANIFEST_SIGNATURE_MISSING"
    RUN_MANIFEST_SIGNATURE_INVALID = "RUN_MANIFEST_SIGNATURE_INVALID"
    RUN_MANIFEST_PAYLOAD_MISMATCH = "RUN_MANIFEST_PAYLOAD_MISMATCH"
    RUN_MANIFEST_LIFECYCLE_MISSING = "RUN_MANIFEST_LIFECYCLE_MISSING"
    RUN_MANIFEST_CHAIN_INVALID = "RUN_MANIFEST_CHAIN_INVALID"
    BACKEND_IDENTITY_REGISTRY_INVALID = "BACKEND_IDENTITY_REGISTRY_INVALID"
    BACKEND_IDENTITY_REGISTRY_SCHEMA_INVALID = "BACKEND_IDENTITY_REGISTRY_SCHEMA_INVALID"
    BACKEND_IDENTITY_NOT_FOUND = "BACKEND_IDENTITY_NOT_FOUND"
    BACKEND_IDENTITY_KEY_NOT_FOUND = "BACKEND_IDENTITY_KEY_NOT_FOUND"
    BACKEND_IDENTITY_KEY_MISMATCH = "BACKEND_IDENTITY_KEY_MISMATCH"
    BACKEND_IDENTITY_KEY_REVOKED = "BACKEND_IDENTITY_KEY_REVOKED"
    BACKEND_IDENTITY_KEY_RETIRED = "BACKEND_IDENTITY_KEY_RETIRED"
    BACKEND_IDENTITY_KEY_EXPIRED = "BACKEND_IDENTITY_KEY_EXPIRED"
    BACKEND_IDENTITY_KEY_NOT_YET_VALID = "BACKEND_IDENTITY_KEY_NOT_YET_VALID"
    BACKEND_IDENTITY_KEY_ROTATION_INVALID = "BACKEND_IDENTITY_KEY_ROTATION_INVALID"
    BACKEND_IDENTITY_SCOPE_MISMATCH = "BACKEND_IDENTITY_SCOPE_MISMATCH"
    BACKEND_IDENTITY_UNTRUSTED = "BACKEND_IDENTITY_UNTRUSTED"
    BACKEND_REGISTRY_SIGNATURE_INVALID = "BACKEND_REGISTRY_SIGNATURE_INVALID"
    BACKEND_REGISTRY_SIGNATURE_MISSING = "BACKEND_REGISTRY_SIGNATURE_MISSING"
    BACKEND_REGISTRY_AUTHORITY_UNTRUSTED = "BACKEND_REGISTRY_AUTHORITY_UNTRUSTED"
    BACKEND_REGISTRY_PROVENANCE_REQUIRED = "BACKEND_REGISTRY_PROVENANCE_REQUIRED"
    BACKEND_REGISTRY_PAYLOAD_MISMATCH = "BACKEND_REGISTRY_PAYLOAD_MISMATCH"
    BACKEND_CAPABILITY_DECLARATION_INVALID = "BACKEND_CAPABILITY_DECLARATION_INVALID"
    BACKEND_CAPABILITY_SCHEMA_INVALID = "BACKEND_CAPABILITY_SCHEMA_INVALID"
    BACKEND_CAPABILITY_SIGNATURE_INVALID = "BACKEND_CAPABILITY_SIGNATURE_INVALID"
    BACKEND_CAPABILITY_UNTRUSTED = "BACKEND_CAPABILITY_UNTRUSTED"
    BACKEND_CAPABILITY_SCOPE_MISMATCH = "BACKEND_CAPABILITY_SCOPE_MISMATCH"
    BACKEND_CAPABILITY_SUBSTRATE_MISMATCH = "BACKEND_CAPABILITY_SUBSTRATE_MISMATCH"
    BACKEND_CAPABILITY_PROFILE_UNSUPPORTED = "BACKEND_CAPABILITY_PROFILE_UNSUPPORTED"
    BACKEND_CAPABILITY_MODE_UNSUPPORTED = "BACKEND_CAPABILITY_MODE_UNSUPPORTED"
    BACKEND_CAPABILITY_DMF_INVALID = "BACKEND_CAPABILITY_DMF_INVALID"
    BACKEND_CAPABILITY_REQUIRED = "BACKEND_CAPABILITY_REQUIRED"
    DMF_CAPABILITIES_INVALID = "DMF_CAPABILITIES_INVALID"
    DMF_PROFILE_UNSUPPORTED = "DMF_PROFILE_UNSUPPORTED"
    DMF_SUBSTRATE_MISMATCH = "DMF_SUBSTRATE_MISMATCH"
    CONFORMANCE_LEVEL_CATALOG_INVALID = "CONFORMANCE_LEVEL_CATALOG_INVALID"
    CONFORMANCE_LEVEL_UNKNOWN = "CONFORMANCE_LEVEL_UNKNOWN"
    CONFORMANCE_LEVEL_DEPENDENCY_MISSING = "CONFORMANCE_LEVEL_DEPENDENCY_MISSING"
    CONFORMANCE_LEVEL_CYCLE = "CONFORMANCE_LEVEL_CYCLE"
    CONFORMANCE_LEVEL_FUTURE_UNSUPPORTED = "CONFORMANCE_LEVEL_FUTURE_UNSUPPORTED"
    CONFORMANCE_LEVEL_TARGET_UNSUPPORTED = "CONFORMANCE_LEVEL_TARGET_UNSUPPORTED"
    CONFORMANCE_LEVEL_CLAIM_INVALID = "CONFORMANCE_LEVEL_CLAIM_INVALID"
    TRUST_POLICY_INVALID = "TRUST_POLICY_INVALID"
    TRUST_POLICY_SCHEMA_INVALID = "TRUST_POLICY_SCHEMA_INVALID"
    TRUST_POLICY_KEY_NOT_FOUND = "TRUST_POLICY_KEY_NOT_FOUND"
    TRUST_POLICY_SCOPE_MISMATCH = "TRUST_POLICY_SCOPE_MISMATCH"
    TRUST_POLICY_KEY_REVOKED = "TRUST_POLICY_KEY_REVOKED"
    RUN_BUNDLE_INVALID = "RUN_BUNDLE_INVALID"
    RUN_BUNDLE_SCHEMA_INVALID = "RUN_BUNDLE_SCHEMA_INVALID"
    RUN_BUNDLE_MISSING_ENTRY = "RUN_BUNDLE_MISSING_ENTRY"
    RUN_BUNDLE_HASH_MISMATCH = "RUN_BUNDLE_HASH_MISMATCH"
    RUN_BUNDLE_PATH_TRAVERSAL = "RUN_BUNDLE_PATH_TRAVERSAL"
    RUN_BUNDLE_SIGNED_CONFORMANCE_FAILED = "RUN_BUNDLE_SIGNED_CONFORMANCE_FAILED"
    RUN_BUNDLE_UNSUPPORTED_FORMAT = "RUN_BUNDLE_UNSUPPORTED_FORMAT"
    INDEPENDENT_VERIFIER_FAILED = "INDEPENDENT_VERIFIER_FAILED"
    VERIFIER_BUNDLE_INVALID = "VERIFIER_BUNDLE_INVALID"
    VERIFIER_HAIL_INVALID = "VERIFIER_HAIL_INVALID"
    VERIFIER_MANIFEST_INVALID = "VERIFIER_MANIFEST_INVALID"
    VERIFIER_TRUST_POLICY_INVALID = "VERIFIER_TRUST_POLICY_INVALID"
    VERIFIER_BINDING_MISMATCH = "VERIFIER_BINDING_MISMATCH"
    ARTIFACT_JSON_INVALID = "ARTIFACT_JSON_INVALID"
    ARTIFACT_INVALID = "ARTIFACT_INVALID"
    ARTIFACT_SCHEMA_INVALID = "ARTIFACT_SCHEMA_INVALID"
    ARTIFACT_KIND_MISSING = "ARTIFACT_KIND_MISSING"
    ARTIFACT_UNSUPPORTED_KIND = "ARTIFACT_UNSUPPORTED_KIND"
    ARTIFACT_UNSUPPORTED_VERSION = "ARTIFACT_UNSUPPORTED_VERSION"
    ARTIFACT_PROFILE_MISSING = "ARTIFACT_PROFILE_MISSING"
    ARTIFACT_PROFILE_MISMATCH = "ARTIFACT_PROFILE_MISMATCH"
    ARTIFACT_PAYLOAD_MISSING = "ARTIFACT_PAYLOAD_MISSING"
    ARTIFACT_PAYLOAD_INVALID = "ARTIFACT_PAYLOAD_INVALID"
    ARTIFACT_HASH_MISMATCH = "ARTIFACT_HASH_MISMATCH"
    RUNBOOK_INVALID = "RUNBOOK_INVALID"
    RUNBOOK_ARTIFACT_MISMATCH = "RUNBOOK_ARTIFACT_MISMATCH"
    RUNBOOK_PROFILE_MISMATCH = "RUNBOOK_PROFILE_MISMATCH"
    TRACE_INVALID = "TRACE_INVALID"
    TRACE_RUNBOOK_MISMATCH = "TRACE_RUNBOOK_MISMATCH"
    TRACE_STEP_MISSING = "TRACE_STEP_MISSING"
    TRACE_STEP_ORDER_INVALID = "TRACE_STEP_ORDER_INVALID"
    TRACE_STATUS_INVALID = "TRACE_STATUS_INVALID"
    ECRP_POLICY_INVALID = "ECRP_POLICY_INVALID"
    ECRP_POLICY_SCHEMA_INVALID = "ECRP_POLICY_SCHEMA_INVALID"
    ECRP_STRATEGY_UNKNOWN = "ECRP_STRATEGY_UNKNOWN"
    ECRP_STRATEGY_NOT_ALLOWED = "ECRP_STRATEGY_NOT_ALLOWED"
    ECRP_ATTEMPTS_EXCEEDED = "ECRP_ATTEMPTS_EXCEEDED"
    ECRP_ATTEMPT_SEQUENCE_INVALID = "ECRP_ATTEMPT_SEQUENCE_INVALID"
    ECRP_TERMINAL_FAILURE_MISSING = "ECRP_TERMINAL_FAILURE_MISSING"
    ECRP_REPLAN_NOT_ALLOWED = "ECRP_REPLAN_NOT_ALLOWED"
    ECRP_TRACE_EVIDENCE_MISSING = "ECRP_TRACE_EVIDENCE_MISSING"
    ECRP_SUCCESS_NOT_SUPPORTED = "ECRP_SUCCESS_NOT_SUPPORTED"
    ECRP_RECOVERY_SUCCESS_NOT_ALLOWED = "ECRP_RECOVERY_SUCCESS_NOT_ALLOWED"
    ECRP_RECOVERY_EVIDENCE_MISSING = "ECRP_RECOVERY_EVIDENCE_MISSING"
    ECRP_RECOVERY_TRACE_INVALID = "ECRP_RECOVERY_TRACE_INVALID"
    ECRP_RECOVERY_STRATEGY_NOT_ALLOWED = "ECRP_RECOVERY_STRATEGY_NOT_ALLOWED"
    ECRP_RECOVERY_UNSUPPORTED = "ECRP_RECOVERY_UNSUPPORTED"
    ECRP_RETRY_STEP_MISSING = "ECRP_RETRY_STEP_MISSING"
    OBSERVATION_POLICY_INVALID = "OBSERVATION_POLICY_INVALID"
    OBSERVATION_POLICY_SCHEMA_INVALID = "OBSERVATION_POLICY_SCHEMA_INVALID"
    OBSERVATION_SNAPSHOT_INVALID = "OBSERVATION_SNAPSHOT_INVALID"
    OBSERVATION_SCHEMA_INVALID = "OBSERVATION_SCHEMA_INVALID"
    OBSERVATION_SOURCE_UNSUPPORTED = "OBSERVATION_SOURCE_UNSUPPORTED"
    OBSERVATION_ATTESTATION_UNSUPPORTED = "OBSERVATION_ATTESTATION_UNSUPPORTED"
    OBSERVATION_CONFIDENCE_INVALID = "OBSERVATION_CONFIDENCE_INVALID"
    OBSERVATION_TRACE_MISMATCH = "OBSERVATION_TRACE_MISMATCH"
    OBSERVATION_RUNBOOK_MISMATCH = "OBSERVATION_RUNBOOK_MISMATCH"
    OBSERVATION_REQUIRED_MISSING = "OBSERVATION_REQUIRED_MISSING"
    OBSERVATION_DMF_STATE_INVALID = "OBSERVATION_DMF_STATE_INVALID"
    HIL_CONTRACT_INVALID = "HIL_CONTRACT_INVALID"
    HIL_CONTRACT_SCHEMA_INVALID = "HIL_CONTRACT_SCHEMA_INVALID"
    HIL_OPERATION_UNSUPPORTED = "HIL_OPERATION_UNSUPPORTED"
    HIL_ESTOP_REQUIRED = "HIL_ESTOP_REQUIRED"
    HIL_ATTESTATION_UNSUPPORTED = "HIL_ATTESTATION_UNSUPPORTED"
    HIL_STATUS_INVALID = "HIL_STATUS_INVALID"
    HIL_STATUS_SCHEMA_INVALID = "HIL_STATUS_SCHEMA_INVALID"
    HIL_FAULT_MISSING_ERROR = "HIL_FAULT_MISSING_ERROR"
    HIL_HARDWARE_CLAIM_UNSUPPORTED = "HIL_HARDWARE_CLAIM_UNSUPPORTED"
    RECORDED_RUN_INVALID = "RECORDED_RUN_INVALID"
    RECORDED_RUN_SCHEMA_INVALID = "RECORDED_RUN_SCHEMA_INVALID"
    RECORDED_RUN_HARDWARE_CLAIM_UNSUPPORTED = "RECORDED_RUN_HARDWARE_CLAIM_UNSUPPORTED"
    RECORDED_RUN_ATTESTATION_UNSUPPORTED = "RECORDED_RUN_ATTESTATION_UNSUPPORTED"
    RECORDED_RUN_TIMESTAMP_UNSUPPORTED = "RECORDED_RUN_TIMESTAMP_UNSUPPORTED"
    RECORDED_RUN_BUNDLE_MISSING = "RECORDED_RUN_BUNDLE_MISSING"
    RECORDED_RUN_BUNDLE_INVALID = "RECORDED_RUN_BUNDLE_INVALID"
    RAW_DEVICE_LOG_INVALID = "RAW_DEVICE_LOG_INVALID"
    RAW_DEVICE_LOG_SCHEMA_INVALID = "RAW_DEVICE_LOG_SCHEMA_INVALID"
    RAW_DEVICE_LOG_ORDER_INVALID = "RAW_DEVICE_LOG_ORDER_INVALID"
    RAW_DEVICE_LOG_ERROR_CODE_MISSING = "RAW_DEVICE_LOG_ERROR_CODE_MISSING"
    RAW_DEVICE_LOG_HASH_MISMATCH = "RAW_DEVICE_LOG_HASH_MISMATCH"
    DMF_ADAPTER_CONFIG_INVALID = "DMF_ADAPTER_CONFIG_INVALID"
    DMF_ADAPTER_SCHEMA_INVALID = "DMF_ADAPTER_SCHEMA_INVALID"
    DMF_ADAPTER_HARDWARE_IO_UNSUPPORTED = "DMF_ADAPTER_HARDWARE_IO_UNSUPPORTED"
    DMF_ADAPTER_PROFILE_UNSUPPORTED = "DMF_ADAPTER_PROFILE_UNSUPPORTED"
    DMF_ADAPTER_ESTOP_REQUIRED = "DMF_ADAPTER_ESTOP_REQUIRED"
    DMF_ADAPTER_STATUS_INVALID = "DMF_ADAPTER_STATUS_INVALID"
    DMF_ADAPTER_DRY_RUN_FAILED = "DMF_ADAPTER_DRY_RUN_FAILED"
    DMF_ADAPTER_ESTOP_ACTIVE = "DMF_ADAPTER_ESTOP_ACTIVE"
    DMF_ADAPTER_RECORDING_FAILED = "DMF_ADAPTER_RECORDING_FAILED"
    OPENDROP_ADAPTER_CONFIG_INVALID = "OPENDROP_ADAPTER_CONFIG_INVALID"
    OPENDROP_ADAPTER_SCHEMA_INVALID = "OPENDROP_ADAPTER_SCHEMA_INVALID"
    OPENDROP_TRANSPORT_CONFIG_INVALID = "OPENDROP_TRANSPORT_CONFIG_INVALID"
    OPENDROP_TRANSPORT_SCHEMA_INVALID = "OPENDROP_TRANSPORT_SCHEMA_INVALID"
    OPENDROP_HARDWARE_IO_UNSUPPORTED = "OPENDROP_HARDWARE_IO_UNSUPPORTED"
    OPENDROP_TRANSPORT_UNSUPPORTED = "OPENDROP_TRANSPORT_UNSUPPORTED"
    OPENDROP_ENDPOINT_UNSUPPORTED_CURRENT_ALPHA = "OPENDROP_ENDPOINT_UNSUPPORTED_CURRENT_ALPHA"
    OPENDROP_MAPPING_INVALID = "OPENDROP_MAPPING_INVALID"
    OPENDROP_MAPPING_DUPLICATE = "OPENDROP_MAPPING_DUPLICATE"
    OPENDROP_CHANNEL_OOB = "OPENDROP_CHANNEL_OOB"
    OPENDROP_COMMAND_INTENT_INVALID = "OPENDROP_COMMAND_INTENT_INVALID"
    OPENDROP_SERIAL_COMMAND_INVALID = "OPENDROP_SERIAL_COMMAND_INVALID"
    OPENDROP_SERIALIZATION_FAILED = "OPENDROP_SERIALIZATION_FAILED"
    OPENDROP_DRY_RUN_FAILED = "OPENDROP_DRY_RUN_FAILED"
    OPENDROP_RECORDING_FAILED = "OPENDROP_RECORDING_FAILED"
    TIMESTAMP_PROFILE_INVALID = "TIMESTAMP_PROFILE_INVALID"
    TIMESTAMP_PROFILE_SCHEMA_INVALID = "TIMESTAMP_PROFILE_SCHEMA_INVALID"
    TIMESTAMP_TOKEN_INVALID = "TIMESTAMP_TOKEN_INVALID"
    TIMESTAMP_TOKEN_SCHEMA_INVALID = "TIMESTAMP_TOKEN_SCHEMA_INVALID"
    TIMESTAMP_TRUSTED_TIME_UNSUPPORTED = "TIMESTAMP_TRUSTED_TIME_UNSUPPORTED"
    TIMESTAMP_TSA_UNSUPPORTED = "TIMESTAMP_TSA_UNSUPPORTED"
    TIMESTAMP_TARGET_HASH_MISMATCH = "TIMESTAMP_TARGET_HASH_MISMATCH"
    TIMESTAMP_TIME_INVALID = "TIMESTAMP_TIME_INVALID"
    TIMESTAMP_SIGNATURE_UNSUPPORTED = "TIMESTAMP_SIGNATURE_UNSUPPORTED"
    ATTESTATION_PROFILE_INVALID = "ATTESTATION_PROFILE_INVALID"
    ATTESTATION_PROFILE_SCHEMA_INVALID = "ATTESTATION_PROFILE_SCHEMA_INVALID"
    ATTESTATION_STATEMENT_INVALID = "ATTESTATION_STATEMENT_INVALID"
    ATTESTATION_STATEMENT_SCHEMA_INVALID = "ATTESTATION_STATEMENT_SCHEMA_INVALID"
    ATTESTATION_HARDWARE_UNSUPPORTED = "ATTESTATION_HARDWARE_UNSUPPORTED"
    ATTESTATION_HARDWARE_ROOT_UNSUPPORTED = "ATTESTATION_HARDWARE_ROOT_UNSUPPORTED"
    ATTESTATION_QUOTE_UNSUPPORTED = "ATTESTATION_QUOTE_UNSUPPORTED"
    ATTESTATION_SIGNATURE_UNSUPPORTED = "ATTESTATION_SIGNATURE_UNSUPPORTED"
    ATTESTATION_SUBJECT_HASH_MISMATCH = "ATTESTATION_SUBJECT_HASH_MISMATCH"
    ATTESTATION_BACKEND_MISMATCH = "ATTESTATION_BACKEND_MISMATCH"
    
    # Envelope & ECRP (Mitigations)
    ENVELOPE_VIOLATION = "ENVELOPE_VIOLATION"             # [Vector 035]
    ECRP_BOUNDS_EXCEEDED = "ECRP_BOUNDS_EXCEEDED"         # Bounded ECRP attempts exhausted
    ECRP_MISSING_EVIDENCE = "ECRP_MISSING_EVIDENCE"       # ECRP attempt without required evidence
    LCP_BOUNDS_EXCEEDED = "ECRP_BOUNDS_EXCEEDED"          # Legacy alias
    LCP_MISSING_EVIDENCE = "ECRP_MISSING_EVIDENCE"        # Legacy alias
    
    # Checkpoints & RImgB/SImgB
    REPLAN_NOT_AT_CHECKPOINT = "REPLAN_NOT_AT_CHECKPOINT" # [Vector 118]
    SIMGB_GEOMETRY_MISMATCH = "SIMGB_GEOMETRY_MISMATCH"
    SIMGB_CALIBRATION_MISMATCH = "SIMGB_CALIBRATION_MISMATCH"
    SIMGB_HASH_MISMATCH = "SIMGB_HASH_MISMATCH"
    RIMGB_SCHEMA_INVALID = "RIMGB_SCHEMA_INVALID"
    DSB_GEOMETRY_MISMATCH = "SIMGB_GEOMETRY_MISMATCH"     # Legacy alias
    CALIBRATION_HASH_MISMATCH = "SIMGB_CALIBRATION_MISMATCH" # Legacy alias
    RSB_SCHEMA_INVALID = "RIMGB_SCHEMA_INVALID"           # Legacy alias

    # --- 6. RUNBOOK: Orchestration ---
    RUNBOOK_SCHEMA_INVALID = "RUNBOOK_SCHEMA_INVALID"     # [Vector 020]
